// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDWWBM4Srzy0FZvkdtO1kkMlKqQ83mvw',
    appId: '1:469768605032:web:7a7ae6c5330533824f9add',
    messagingSenderId: '469768605032',
    projectId: 'campuslost-bd070',
    authDomain: 'campuslost-bd070.firebaseapp.com',
    storageBucket: 'campuslost-bd070.firebasestorage.app',
    measurementId: 'G-5YYG7VFCS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDAzY93Itj4gjtq_o9XnlzoYTyq3gBwQ',
    appId: '1:469768605032:android:1856003ffa4555cd4f9add',
    messagingSenderId: '469768605032',
    projectId: 'campuslost-bd070',
    storageBucket: 'campuslost-bd070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-30vAFSQmSe7MX-tfs6Gm1BCHKUqP4SY',
    appId: '1:469768605032:ios:634fbd5ccd0a80b04f9add',
    messagingSenderId: '469768605032',
    projectId: 'campuslost-bd070',
    storageBucket: 'campuslost-bd070.firebasestorage.app',
    iosBundleId: 'com.example.campuslost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-30vAFSQmSe7MX-tfs6Gm1BCHKUqP4SY',
    appId: '1:469768605032:ios:634fbd5ccd0a80b04f9add',
    messagingSenderId: '469768605032',
    projectId: 'campuslost-bd070',
    storageBucket: 'campuslost-bd070.firebasestorage.app',
    iosBundleId: 'com.example.campuslost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDWWBM4Srzy0FZvkdtO1kkMlKqQ83mvw',
    appId: '1:469768605032:web:145b7fb55ebec0354f9add',
    messagingSenderId: '469768605032',
    projectId: 'campuslost-bd070',
    authDomain: 'campuslost-bd070.firebaseapp.com',
    storageBucket: 'campuslost-bd070.firebasestorage.app',
    measurementId: 'G-YQX8F3JHLG',
  );
}
